thresholds:
  deauth_per_sec: 1
  probe_req_per_sec: 4
  beacon_per_sec: 66
  deauth_per_sec_bssid: 1
windows_sec:
  deauth: 5
  probe_req: 5
  beacon: 5
  stats_interval: 1
  evil_twin_window: 5
evil_twin:
  distinct_bssids_threshold: 3
anomaly:
  use_zscore: true
  z_threshold: 3.0
deauth_reason:
  distinct_threshold: 3
  common_whitelist:
  - 1
  - 4
  - 8
channel:
  beacon_spike_min_count: 100
  beacon_spike_dom_ratio: 2.0
alerting:
  cooldown_sec: 5.0
learning:
  safe_z_gate: 6.0
baselines:
  n: 50
  deauth:
    mean: 0.0
    std: 1.0
  probe:
    mean: 0.6976744186046512
    std: 1.0237842187467505
  beacon:
    mean: 43.18604651162791
    std: 7.51202389337127
