thresholds:
  deauth_per_sec: 1
  probe_req_per_sec: 134
  beacon_per_sec: 253
  deauth_per_sec_bssid: 1
windows_sec:
  deauth: 5
  probe_req: 5
  beacon: 5
  stats_interval: 1
  evil_twin_window: 5
evil_twin:
  distinct_bssids_threshold: 3
anomaly:
  use_zscore: true
  z_threshold: 3.0
deauth_reason:
  distinct_threshold: 3
  common_whitelist:
  - 1
  - 4
  - 8
channel:
  beacon_spike_min_count: 200
  beacon_spike_dom_ratio: 2.0
alerting:
  cooldown_sec: 5.0
learning:
  safe_z_gate: 6.0
baselines:
  n: 249
  deauth:
    mean: 0.0
    std: 1.0
  probe:
    mean: 36.41767068273092
    std: 32.24520525666042
  beacon:
    mean: 157.71485943775102
    std: 31.64643752640686
